### PR TITLE
adding support for VersionVault version control tool

### PR DESCRIPTION
**Pull request by niteshhibarehcl**
Hi,

Kindly review and merge the code

### CODE REVIEW

**Comment by rombert** [comment]
Thanks for the PR @niteshhibarehcl . I can't test it out since I don't have access to VersionVault, can you please confirm that there are no further changes that you need except for this PR to be merged?

**Comment by niteshhibarehcl** [comment]
Hi @rombert , Thank you for your quick response. Yes, there will be no further changes.

**Comment by rombert** [comment]
Thanks @niteshhibarehcl , merged.

**Comment by niteshhibarehcl** [comment]
Thank you @rombert

**Pull request merged**
